<?php
/*  Riichi mahjong API game server
 *  Copyright (C) 2016  o.klimenko aka ctizen
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace Riichi;

require_once __DIR__ . '/../Controller.php';
require_once __DIR__ . '/../helpers/Seating.php';

class SeatingController extends Controller
{
    /**
     * Generate new seating
     *
     * @param int $eventId
     * @param int $groupsCount
     * @param int $seed
     * @throws AuthFailedException
     * @throws InvalidParametersException
     * @return array
     */
    public function generate($eventId, $groupsCount, $seed)
    {
        if (!(new EventModel($this->_db, $this->_config))->checkAdminToken()) {
            throw new AuthFailedException('Authentication failed! Ask for some assistance from admin team', 403);
        }

        $this->_log->addInfo('Generating seating for event #' . $eventId);
        list ($playersMap, $tables) = $this->_getData($eventId);
        $seating = Seating::generateTables($playersMap, $tables, $groupsCount, $seed);
        $intersections = Seating::makeIntersectionsTable($seating, $tables);
        $this->_log->addInfo('Successfully generated seating for event #' . $eventId);

        return [
            'seed' => $seed,
            'seating' => array_map(function ($id, $score) {
                return [
                    'id' => $id,
                    'score' => $score
                ];
            }, array_keys($seating), array_values($seating)),
            'intersections' => $intersections
        ];
    }

    /**
     * Approve seating generated by seed and start all games
     *
     * @param int $eventId
     * @param int $groupsCount
     * @param int $seed
     * @throws InvalidParametersException
     * @throws AuthFailedException
     * @return bool
     */
    public function startGamesWithSeating($eventId, $groupsCount, $seed)
    {
        if (!(new EventModel($this->_db, $this->_config))->checkAdminToken()) {
            throw new AuthFailedException('Authentication failed! Ask for some assistance from admin team', 403);
        }

        $this->_log->addInfo('Starting new games by seed #' . $seed . ' for event #' . $eventId);
        $sessions = SessionPrimitive::findByEventAndStatus($this->_db, $eventId, 'inprogress');
        if (!empty($sessions)) {
            throw new InvalidParametersException('Failed to start new game: not all games finished in event id#' . $eventId);
        }

        list ($playersMap, $tables) = $this->_getData($eventId);
        $seating = array_chunk(array_keys(Seating::generateTables($playersMap, $tables, $groupsCount, $seed)), 4);
        foreach ($seating as $table) {
            (new InteractiveSessionModel($this->_db, $this->_config))
                ->startGame($eventId, $table);
        }

        $this->_log->addInfo('Started all games by seed #' . $seed . ' for event #' . $eventId);
        return true;
    }

    /**
     * @param $eventId
     * @return array
     * @throws InvalidParametersException
     */
    protected function _getData($eventId)
    {
        $playersMap = [];
        
        $event = EventPrimitive::findById($this->_db, [$eventId]);
        if (empty($event)) {
            throw new InvalidParametersException('Event id#' . $eventId . ' not found in DB');
        }
        
        $histories = PlayerHistoryPrimitive::findLastByEvent($this->_db, $eventId);
        if (!empty($histories)) {
            foreach ($histories as $h) {
                $playersMap[$h->getPlayerId()] = $h->getRating();
            }
        } else {
            $initialRating = $event[0]->getRuleset()->startRating();
            $playersReg = PlayerRegistrationPrimitive::findRegisteredPlayersIdsByEvent($this->_db, $eventId);
            foreach ($playersReg as $id) {
                $playersMap[$id] = $initialRating;
            }
        }

        $seatingInfo = SessionPrimitive::getPlayersSeatingInEvent($this->_db, $eventId);
        $tables = array_chunk(array_map(function ($el) {
            return $el['user_id'];
        }, $seatingInfo), 4);

        return [$playersMap, $tables];
    }
}
